"""Import all vial label applicator STL components into Blender at correct positions.

Designed to be executed via blender-mcp's execute_blender_code tool.
Expects STL files in models/components/ relative to the project root.
"""

import json
import math

import bpy
import os
from mathutils import Vector

# Project root — derived from script location.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
COMPONENTS_DIR = os.path.join(PROJECT_ROOT, "models", "components")

# Load component positions from the assembly manifest generated by frame.py.
# This keeps frame.py as the single source of truth for component layout.
_manifest_path = os.path.join(PROJECT_ROOT, "models", "assembly_manifest.json")
try:
    with open(_manifest_path, "r") as _f:
        _manifest = json.load(_f)
    COMPONENTS = [
        {
            "file": entry["file"],
            "location": tuple(entry["position"]),
            "rotation": tuple(entry["rotation"]),
            "color": tuple(entry["color"]),
            "name": entry["name"],
        }
        for entry in _manifest
    ]
except (FileNotFoundError, json.JSONDecodeError) as _e:
    print(f"WARNING: Could not load assembly manifest ({_e})")
    COMPONENTS = []


def clear_scene():
    """Remove all existing mesh objects."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def import_stl(filepath, name, location, rotation, color):
    """Import an STL file and apply transforms and material."""
    if not os.path.exists(filepath):
        print(f"WARNING: {filepath} not found, skipping")
        return None

    bpy.ops.wm.stl_import(filepath=filepath)
    obj = bpy.context.active_object
    obj.name = name

    # STL units are mm; scale object to meters for Blender.
    obj.scale = (0.001, 0.001, 0.001)
    obj.location = Vector(location) * 0.001
    obj.rotation_euler = tuple(math.radians(r) for r in rotation)

    # Apply material with color.
    mat = bpy.data.materials.new(name=f"Mat_{name}")
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = color
        bsdf.inputs["Roughness"].default_value = 0.5
    obj.data.materials.append(mat)

    return obj


def setup_assembly():
    """Import all components and arrange in assembly."""
    clear_scene()

    imported = []
    for comp in COMPONENTS:
        filepath = os.path.join(COMPONENTS_DIR, comp["file"])
        obj = import_stl(
            filepath,
            comp["name"],
            comp["location"],
            comp["rotation"],
            comp["color"],
        )
        if obj:
            imported.append(obj)

    print(f"Imported {len(imported)}/{len(COMPONENTS)} components")
    return imported


if __name__ == "__main__":
    setup_assembly()
